# Generated by Django 4.0.1 on 2022-01-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0004_badge_unit_alter_perk_required_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
