# Generated by Django 4.0.1 on 2022-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0005_alter_badge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
