# Generated by Django 4.0.1 on 2022-01-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0006_alter_badge_name_alter_badge_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='restricted_text',
            field=models.TextField(default='No restricted text here, all is open!', help_text='This is the restricted text that will appear after someone has claimed this perk. This can include details on next steps of how to claim the perk'),
            preserve_default=False,
        ),
    ]
