# Generated by Django 4.0.1 on 2022-01-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_badges_user_perks_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
